version: '3.8'

services:
  tests:
    build:
      context: ./python_registry_api
      dockerfile: Dockerfile.test
    command: pytest -v -s
    environment:
      - PROD_DB=False
    depends_on:
      - api
      - frontend
  api:
    build:
      context: ./python_registry_api
      dockerfile: Dockerfile
    entrypoint: sh startup.sh
    hostname: registryapi
    environment:
      - PROD_DB=False
    ports:
      - 5000:5000
  frontend:
    build: ./vue_registry_frontend
    command: "nginx -g \"daemon off;\""
    hostname: registryfrontend
    ports:
      - 80:80
