version: '3.8'

services:
  tests:
    build:
      context: ./python_registry_api
      dockerfile: Dockerfile.test
    entrypoint: sh test.sh
    depends_on:
      - api
      - frontend
  api:
    build:
      context: ./python_registry_api
      dockerfile: Dockerfile
    entrypoint: sh startup.sh
    hostname: testapi
    ports:
      - 5000:5000
    depends_on:
      - db
  frontend:
    build: ./vue_registry_frontend
    command: "nginx -g \"daemon off;\""
    hostname: testfrontend
    ports:
      - 80:80
  db:
    image: postgres:13-alpine
    env_file:
      - ./env/postgres.dev
